package middleware

import (
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"go.uber.org/zap"

	"trimble.com/common/constants"
	"trimble.com/common/requestcontext"
)

// RequestIdMiddleware -> struct for requestId
type RequestIdMiddleware struct {
	logger *zap.Logger
}

// NewRequestIdMiddleware -> new instance of RequestIdMiddleware
func NewRequestIdMiddleware(logger *zap.Logger) RequestIdMiddleware {
	return RequestIdMiddleware{
		logger: logger,
	}
}

// HandleRequestId -> It sets up the RequestId middleware
func (m RequestIdMiddleware) HandleRequestId() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Get id from request
		requestId := c.GetHeader(constants.RequestIdAzureHeaderKey)
		if requestId == "" {
			requestId = c.GetHeader(constants.RequestIdAWSHeaderKey)
		}
		if requestId == "" {
			// The "standard" header generated by the infrastructure is missing. Generate own id and add custom header to request and response.
			requestId = uuid.New().String()
			c.Request.Header.Add(constants.RequestIdTrimbleHeaderKey, requestId)
			c.Header(constants.RequestIdTrimbleHeaderKey, requestId)
		}
		// Create request context for this request
		// RequestContext holds contextual information for this request
		ctx := requestcontext.NewRequestContext(requestId, m.logger)
		ctx.SetHttpRequest(c.Request)
		c.Set(constants.RequestCtx, ctx)
		c.Next()
	}
}
