sonar.projectKey=TrimbleConnect.ConnectedDataEnvironment:TrimbleDrive
sonar.projectName=TrimbleConnect - ConnectedDataEnvironment - TrimbleDrive

sonar.sources=src
sonar.exclusions=**/*_test.go,**/*_generated*.go,**/*_generated/**,**/vendor/**,**/*_mock.go

sonar.tests=src
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/*_generated*.go,**/*_generated/**,**/vendor/**,**/*_mock.go

sonar.verbose=true

sonar.python.version=3.8

#sonar.go.tests.reportPaths=report.json
#sonar.go.coverage.reportPaths=code-coverage-report.out
#sonar.go.golangci-lint.reportPaths=golangci-lint.out
