---
mongo:
  uri: "mongodb+srv://<username>:<password>@trimbledrivedevelopment.dfq1n.mongodb.net/?retryWrites=true&w=majority"
  dbname: "tdrive"
kafka:
  brokers:
  apiKey:
  apiSecret:
  groupId:
  topic:
  deadLetterTopic:
  # Adjustable batch size, can be fine-tuned based on the system behaviour
  # keeping in mind about real factors
  batchSize: 25
