"""This module stores the constant variables"""
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
STORAGE_PATH_SEPARATOR = "/"
DEFAULT_STORAGE_DIR = "orig"
THUMB_STORAGE_DIR = "thumb"
UPLOAD_STATUS_UPLOADABLE = "UPLOADABLE"
UPLOAD_STATUS_ERROR = "ERROR"
CONTENT_STATUS_AVAILABLE = "AVAILABLE"
CONTENT_STATUS_ERROR = "ERROR"
